### ISSUE TITLE
Feature request:  CLI tool

### ISSUE THREAD

**Issue by JustinBeckwith** [ofrobots/require-so-slow#1]
This library is rad sauce.  However, I am finding that when I want to use it, it's usually a one off where I don't want to write code.  I'd love to just do this:

```
$ npm install -g require-so-slow
$ rss googleapis
```

This would just drop a `googleapis.trace` in the CWD.  If I wanted, I could be explicit:

```
$ rss googleapis@24 g24.trace
```

Happy to contribute if you think this makes sense in this repo 👍

**Comment by ofrobots** [comment]
That would be awesome. Happy to take contributions :)
