### ISSUE TITLE
Ability to upload the trace and render using a web-based tool

### ISSUE THREAD

**Issue by ofrobots** [ofrobots/require-so-slow#4]
- [ ] Fix Chrome DevTools timeline viewer to be able to render generic traces.
- [ ] Ability to upload the traces somewhere when an `--upload` flag is specified
- [ ] Automatically open the trace using https://chromedevtools.github.io/timeline-viewer – a hosted version of Chrome DevTools timeline viewer.

**Comment by flaviut** [comment]
This trace works really well with https://www.speedscope.app/ -- I find that UI much more intuitive than the chrome timeline viewer.
